### ISSUE TITLE
index.html not outputting

### ISSUE THREAD

**Issue by PepperInsure** [CISC-475-Team-2/Front-End#24]
Not sure what happened, when I tried to make a commit after playing with word distance there were some changes, but I never saw a commit after mine. Then when trying to run the index.html after the update nothing was working.

Did someone change the code?

**Comment by PepperInsure** [comment]
Decided to revert back to to a previous branch due to conflicts. I still have the old branch saved just in case this was some kind of mishap and the changes were meant to be there. If so, please leave a comment saying so.

**Comment by hermetic-charm** [comment]
@PepperInsure Okay so I looked into the history, here is what happened:  Your last commit was Nov 11th, after that I made 7 more commits.  It looks like when you started working again you didn't pull those changes down.  Among my commits were a number of things, some new functionality and fixes.  I went through your latest commits from today after your revert and actually the changes you made were already implemented.  Additionally when you reverted you reverted back to your last commit, not the most recent stable commit, which wiped out my 7 commits.

I would have just reverted your revert but I couldn't because it was corrupt, I don't know how because I have never  seen it happen before but your revert commit was corrupt (i.e. git show 7d3fa0b returned bad object).  So I had to do a hard reset back to my last commit (8c1bba0), which you really shouldn't do but I had no choice since the revert merge commit was corrupt.  With that in mind, anyone that was working out of master should definitely definitely pull and make sure you are on the same page as git reset can do some funky things, make sure you are on 8c1bba0 (if you open shell do "git log" and shoul be the beginning of the hash of the latest commit).

Now, like I said I looked at your latest commits, restoring my commits includes those changes as they were already implemented.  So you don't have to worry about going back and re-applying them.  Everything is up to date now.

As one final note, we have migrated the project into an MVC project so you may want to move over to that for future changes as it will likely be our final product.
